#define BG '${background}'
#define FG '${foreground}'

#define BLK '${BLK}'
#define RED '${RED}'
#define GRN '${GRN}'
#define YEL '${YEL}'
#define BLU '${BLU}'
#define MAG '${MAG}'
#define CYN '${CYN}'
#define WHT '${WHT}'

#define BBLK '${BLK}'
#define BRED '${BRED}'
#define BGRN '${BGRN}'
#define BYEL '${BYEL}'
#define BBLU '${BBLU}'
#define BMAG '${BMAG}'
#define BCYN '${BCYN}'
#define BWHT '${BWHT}'